"""
scripts_p3/score_coco_real.py

We produce outputs_p3/scores/coco_real_scores.csv here; 08c_eval_coco_real_fpr.py (E7) consumes it.

We use MS-COCO val 2017, 1000 real photographs (no SD generation),
each evaluated under `none` and `jpeg(q=50)`. Clean only (no watermark,
label = 0 by construction). At evaluation time (08c) we use the seed-0-calibrated
M3 threshold (reused, not recalibrated on COCO data).

CUDA backend (RunPod). We reuse the same ROBIN DDIM-inversion scoring machinery
as our main scoring pass (CudaRobinPipe / batched_ring_distance), just with a different,
much smaller image source (1000 real photos x 2 attacks x 1 label = 2000
items, vs 170,000 for our main ROBIN evaluation) and no watermarked
counterpart (real photos were never generated by SD, so ROBIN cannot have
embedded a watermark in them).

Determinism: we select 1000 images from val2017 (5000 images) via
random.Random(coco_shuffle_seed).shuffle(sorted(filenames))[:1000], matching
the coco_shuffle_seed=0 invariant we already use elsewhere in this pipeline.

Usage:
    python scripts_p3/score_coco_real.py \
        --coco_dir /workspace/coco/val2017 --num_images 1000 \
        --coco_shuffle_seed 0 --batch_size 32
Our output columns: image_id, attack_id, score_z
"""
from __future__ import annotations

import argparse
import io
import random
import sys
from pathlib import Path

import numpy as np
import torch
from PIL import Image

_ROBIN_DIR = str(Path(__file__).resolve().parents[2] / "robin_official")
sys.path.insert(0, _ROBIN_DIR)
from inverse_stable_diffusion import InversableStableDiffusionPipeline  # noqa: E402
from diffusers import DPMSolverMultistepScheduler  # noqa: E402
from optim_utils import get_watermarking_mask, transform_img  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _attack_scoring_common import batched_ring_distance, WmArgs  # noqa: E402

ATTACKS = ["none", "jpeg_q50"]


def apply_attack(img: Image.Image, attack_id: str) -> Image.Image:
    if attack_id == "none":
        return img
    if attack_id == "jpeg_q50":
        buf = io.BytesIO()
        img.save(buf, format="JPEG", quality=50)
        buf.seek(0)
        return Image.open(buf).convert("RGB")
    raise NotImplementedError(attack_id)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--coco_dir", type=Path, default=Path("/workspace/coco/val2017"))
    ap.add_argument("--num_images", type=int, default=1000)
    ap.add_argument("--coco_shuffle_seed", type=int, default=0)
    ap.add_argument("--wm_ckpt", default=str(Path(__file__).resolve().parents[2] / "robin_official" / "ckpts" / "optimized_r5_15_step10.pt"))
    ap.add_argument("--out", type=Path, default=Path("outputs_p3/scores/coco_real_scores.csv"))
    # stabilityai/stable-diffusion-2-1-base is gated (HTTP 401); we use this open mirror.
    ap.add_argument("--model_id", default="sd2-community/stable-diffusion-2-1-base")
    # the mirror has no fp16 branch; we get fp16 from torch_dtype, not from this.
    ap.add_argument("--variant", default=None)
    ap.add_argument("--device", default="cuda")
    ap.add_argument("--steps", type=int, default=35)
    ap.add_argument("--num_inference_steps", type=int, default=50)
    ap.add_argument("--batch_size", type=int, default=32)
    ap.add_argument("--checkpoint_every", type=int, default=50)
    args = ap.parse_args()

    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

    all_files = sorted(p.name for p in args.coco_dir.glob("*.jpg"))
    rng = random.Random(args.coco_shuffle_seed)
    rng.shuffle(all_files)
    selected = all_files[: args.num_images]
    print(f"[coco] {len(all_files)} available, selected {len(selected)} (shuffle_seed={args.coco_shuffle_seed})")

    scheduler = DPMSolverMultistepScheduler.from_pretrained(args.model_id, subfolder="scheduler")
    if not hasattr(scheduler, "final_alpha_cumprod"):
        scheduler.final_alpha_cumprod = torch.tensor(1.0)
    pipe = InversableStableDiffusionPipeline.from_pretrained(
        args.model_id, scheduler=scheduler, safety_checker=None,
        torch_dtype=torch.float16, variant=args.variant,
    ).to(args.device)

    null_emb = pipe.get_text_embedding("")
    ckpt = torch.load(args.wm_ckpt, map_location="cpu")
    opt_wm = ckpt["opt_wm"].to(torch.complex64).to(args.device)
    ref = pipe.get_random_latents()
    watermarking_mask = get_watermarking_mask(ref, WmArgs(), args.device)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    items = {}
    if args.out.exists():
        import csv as _csv
        with args.out.open(newline="", encoding="utf-8") as f:
            for row in _csv.DictReader(f):
                items[(row["image_id"], row["attack_id"])] = {
                    "image_id": row["image_id"], "attack_id": row["attack_id"],
                    "score_z": float(row["score_z"])}
    done_ids = set(items.keys())

    def score_batch(imgs):
        b = len(imgs)
        t = torch.cat([transform_img(im).unsqueeze(0) for im in imgs], dim=0).to(torch.float32)
        t = t.to(device=args.device, dtype=pipe.text_encoder.dtype)
        lat = pipe.get_image_latents(t, sample=False)
        text_emb = null_emb.expand(b, -1, -1)
        buf = [lat]
        _, buf, _ = pipe.forward_diffusion(
            latents=lat, text_embeddings=text_emb, guidance_scale=1.0,
            num_inference_steps=args.num_inference_steps, latents_b=buf)
        dists = batched_ring_distance(buf[args.steps], opt_wm, watermarking_mask)
        return [float(d) for d in dists]

    pending_imgs, pending_keys = [], []
    for fn in selected:
        image_id = fn.rsplit(".", 1)[0]
        img = Image.open(args.coco_dir / fn).convert("RGB")
        for atk in ATTACKS:
            if (image_id, atk) in done_ids:
                continue
            pending_imgs.append(apply_attack(img, atk))
            pending_keys.append((image_id, atk))

    def checkpoint():
        import csv as _csv
        with args.out.open("w", newline="", encoding="utf-8") as f:
            w = _csv.DictWriter(f, fieldnames=["image_id", "attack_id", "score_z"])
            w.writeheader()
            w.writerows(items.values())

    for lo in range(0, len(pending_imgs), args.batch_size):
        chunk_imgs = pending_imgs[lo:lo + args.batch_size]
        chunk_keys = pending_keys[lo:lo + args.batch_size]
        dists = score_batch(chunk_imgs)
        for (iid, atk), d in zip(chunk_keys, dists):
            items[(iid, atk)] = {"image_id": iid, "attack_id": atk, "score_z": -d}
        if (lo // args.batch_size) % max(args.checkpoint_every // args.batch_size, 1) == 0:
            checkpoint()
            print(f"[coco] scored {len(items)}/{len(selected) * len(ATTACKS)}")

    checkpoint()
    print(f"[coco] done: {len(items)} items -> {args.out}")


if __name__ == "__main__":
    main()
